export const typeColors: Record<string, string> = {
  full: "#1C3160",
  short: "#FDBB30",
  panel: "#A20A35",
  workshop: "#f4a261",
  tutorial: "#A20A35",
  vis: "#FDBB30",
  poster: "#1C3160",
  invited: "#1C3160",
  visap: "#2672B9",
  challenges: "#2672B9",
  symposium: "#2672B9",
  associated: "#2672B9",
  meetup: "#A20A35",
  live: "#A20A35",
  application: "#F15722",
  memorial: "#FDBB30",
  supporter: "#FDBB30",
  keynote: "#FDBB30",
  capstone: "#FDBB30",
  industry: "#FDBB30",
};

export const typeTextColors: Record<string, string> = {
  full: "#ffffff",
  short: "#111827",
  panel: "#ffffff",
  workshop: "#ffffff",
  tutorial: "#ffffff",
  vis: "#ffffff",
  poster: "#ffffff",
  invited: "#ffffff",
  visap: "#ffffff",
  challenges: "#ffffff",
  symposium: "#ffffff",
  associated: "#ffffff",
  meetup: "#ffffff",
  live: "#ffffff",
  application: "#ffffff",
  memorial: "#ffffff",
  supporter: "#ffffff",
  keynote: "#ffffff",
  capstone: "#ffffff",
  industry: "#ffffff",
};
